-- Restore the ClickUp dates on 61 imported comments.
--
-- GENERATED by scripts/backfill-comment-dates.mjs. Do not hand-edit: it is keyed
-- by comment id, and those ids exist only in the project it was generated
-- against. On any other database every statement here matches zero rows, which
-- is why it lives outside supabase/migrations/ and never replays.
--
-- ⚠️ APPLY BY HAND in the Supabase SQL editor.
--
-- ⚠️ THE TRIGGER IS DISABLED AROUND IT, AND THAT IS THE WHOLE POINT.
-- `vizserve_pms_set_updated_at()` sets `new.updated_at = now()` on every
-- update, so without this the "edited" mark this is trying to clear would be
-- re-applied by the very statement clearing it. Re-enabled in the same
-- transaction: a failure rolls the disable back with everything else.
--
-- `vizserve_pms_task_comments_notify` is AFTER INSERT only, so no inbox
-- notification is raised by any of this.

begin;

alter table vizserve_pms_task_comments disable trigger vizserve_pms_task_comments_updated_at;
update vizserve_pms_task_comments set created_at = '2025-11-20 13:21:42+08'::timestamptz, updated_at = '2025-11-20 13:21:42+08'::timestamptz where id = '44cbbdf5-773c-542d-9bdd-e127bf434ed0';
update vizserve_pms_task_comments set created_at = '2025-10-13 09:55:56+08'::timestamptz, updated_at = '2025-10-13 09:55:56+08'::timestamptz where id = '12587ae0-7dfd-52fd-a177-960ac6e44bcf';
update vizserve_pms_task_comments set created_at = '2025-10-13 09:54:10+08'::timestamptz, updated_at = '2025-10-13 09:54:10+08'::timestamptz where id = 'b5181d56-4342-5ad5-b856-291c529bb708';
update vizserve_pms_task_comments set created_at = '2025-11-10 15:10:56+08'::timestamptz, updated_at = '2025-11-10 15:10:56+08'::timestamptz where id = '813d2e05-a7c4-5fac-94b7-50800fc27571';
update vizserve_pms_task_comments set created_at = '2025-10-13 18:03:33+08'::timestamptz, updated_at = '2025-10-13 18:03:33+08'::timestamptz where id = 'e59b6f33-eaf8-5735-abdb-904a3f06eb21';
update vizserve_pms_task_comments set created_at = '2025-10-13 18:01:15+08'::timestamptz, updated_at = '2025-10-13 18:01:15+08'::timestamptz where id = '29f947b8-6c49-5556-8a09-0997338c64f7';
update vizserve_pms_task_comments set created_at = '2025-10-13 17:54:53+08'::timestamptz, updated_at = '2025-10-13 17:54:53+08'::timestamptz where id = 'a755f47f-54d4-5126-a2e7-4a162c7c90e2';
update vizserve_pms_task_comments set created_at = '2025-11-10 14:21:30+08'::timestamptz, updated_at = '2025-11-10 14:21:30+08'::timestamptz where id = '108373de-f143-5383-b9e1-7e91e32a86f2';
update vizserve_pms_task_comments set created_at = '2025-11-10 14:13:43+08'::timestamptz, updated_at = '2025-11-10 14:13:43+08'::timestamptz where id = '95944269-c5b4-5f6f-bf11-a74a6eda6984';
update vizserve_pms_task_comments set created_at = '2025-11-10 14:10:39+08'::timestamptz, updated_at = '2025-11-10 14:10:39+08'::timestamptz where id = 'aef75ad2-0860-54ae-ba39-c60eb4c3a0c4';
update vizserve_pms_task_comments set created_at = '2025-11-06 20:39:26+08'::timestamptz, updated_at = '2025-11-06 20:39:26+08'::timestamptz where id = '51907c18-12c0-51f3-86cb-5ded6226a671';
update vizserve_pms_task_comments set created_at = '2025-11-06 20:32:00+08'::timestamptz, updated_at = '2025-11-06 20:32:00+08'::timestamptz where id = '1ff2a92f-8268-5c27-8770-1d7894d7b741';
update vizserve_pms_task_comments set created_at = '2025-12-09 09:42:08+08'::timestamptz, updated_at = '2025-12-09 09:42:08+08'::timestamptz where id = '8a8e4f63-6896-5778-be97-b956d32a51e1';
update vizserve_pms_task_comments set created_at = '2025-12-09 09:39:51+08'::timestamptz, updated_at = '2025-12-09 09:39:51+08'::timestamptz where id = 'cf7821e6-fcc9-5eef-9a8c-c1958078d054';
update vizserve_pms_task_comments set created_at = '2025-12-09 09:26:08+08'::timestamptz, updated_at = '2025-12-09 09:26:08+08'::timestamptz where id = '4a5a2eb8-43c6-5041-ac12-20faf8f37e13';
update vizserve_pms_task_comments set created_at = '2025-12-09 09:24:07+08'::timestamptz, updated_at = '2025-12-09 09:24:07+08'::timestamptz where id = '5a76f1c6-87c2-5b26-9ee2-68480cb687d2';
update vizserve_pms_task_comments set created_at = '2025-12-09 09:20:56+08'::timestamptz, updated_at = '2025-12-09 09:20:56+08'::timestamptz where id = 'ae6effcf-f924-5c4b-a79c-9afe5d4e783e';
update vizserve_pms_task_comments set created_at = '2025-12-09 09:18:44+08'::timestamptz, updated_at = '2025-12-09 09:18:44+08'::timestamptz where id = '2d747dd7-6084-57e4-8a21-3c5e8d0e1328';
update vizserve_pms_task_comments set created_at = '2025-12-09 09:16:00+08'::timestamptz, updated_at = '2025-12-09 09:16:00+08'::timestamptz where id = '0a917e0c-d5cc-5352-91f3-f72429b322cf';
update vizserve_pms_task_comments set created_at = '2026-03-17 09:41:46+08'::timestamptz, updated_at = '2026-03-17 09:41:46+08'::timestamptz where id = '2cb8a5f9-4c34-5d99-89d8-2e9b24f88db3';
update vizserve_pms_task_comments set created_at = '2026-03-17 09:34:57+08'::timestamptz, updated_at = '2026-03-17 09:34:57+08'::timestamptz where id = 'eb457b4b-e6c3-5749-8bae-abbefe056a2e';
update vizserve_pms_task_comments set created_at = '2026-03-17 09:32:35+08'::timestamptz, updated_at = '2026-03-17 09:32:35+08'::timestamptz where id = '454dc91a-5b16-53eb-b66c-97bbceda830a';
update vizserve_pms_task_comments set created_at = '2026-03-17 09:29:05+08'::timestamptz, updated_at = '2026-03-17 09:29:05+08'::timestamptz where id = 'eced74af-ed4f-534a-bd1f-e677188bf400';
update vizserve_pms_task_comments set created_at = '2026-03-17 09:28:00+08'::timestamptz, updated_at = '2026-03-17 09:28:00+08'::timestamptz where id = 'b1a9710b-be91-5ee4-82ec-030f8311282e';
update vizserve_pms_task_comments set created_at = '2026-03-17 09:23:17+08'::timestamptz, updated_at = '2026-03-17 09:23:17+08'::timestamptz where id = '8c41417a-6b29-58c2-a19e-3aeaa860eeb6';
update vizserve_pms_task_comments set created_at = '2026-03-17 09:21:22+08'::timestamptz, updated_at = '2026-03-17 09:21:22+08'::timestamptz where id = 'b0579640-e424-57d6-97dd-4e991ac105c3';
update vizserve_pms_task_comments set created_at = '2026-03-17 09:20:31+08'::timestamptz, updated_at = '2026-03-17 09:20:31+08'::timestamptz where id = '68a7a4d8-dbad-52a0-a1ba-cb3dff7b5a90';
update vizserve_pms_task_comments set created_at = '2026-05-12 19:36:14+08'::timestamptz, updated_at = '2026-05-12 19:36:14+08'::timestamptz where id = '77e9be8c-6c55-5fb9-a7a4-64c6b1af5399';
update vizserve_pms_task_comments set created_at = '2026-05-12 19:34:01+08'::timestamptz, updated_at = '2026-05-12 19:34:01+08'::timestamptz where id = '244a8835-1b40-58b1-bb84-08c2b698db9b';
update vizserve_pms_task_comments set created_at = '2026-05-12 19:28:48+08'::timestamptz, updated_at = '2026-05-12 19:28:48+08'::timestamptz where id = 'c9bdcc7a-35b4-5bd1-8fec-f61a456dfb52';
update vizserve_pms_task_comments set created_at = '2026-05-12 19:27:13+08'::timestamptz, updated_at = '2026-05-12 19:27:13+08'::timestamptz where id = '3ba04554-4832-5d0c-ae84-ddf7e1fe0211';
update vizserve_pms_task_comments set created_at = '2026-05-12 19:25:35+08'::timestamptz, updated_at = '2026-05-12 19:25:35+08'::timestamptz where id = 'b04d7932-cb53-5be9-b61c-c643b7a52a39';
update vizserve_pms_task_comments set created_at = '2026-05-12 19:25:11+08'::timestamptz, updated_at = '2026-05-12 19:25:11+08'::timestamptz where id = 'de62925d-ac6d-59e8-a33c-a99d46afbed8';
update vizserve_pms_task_comments set created_at = '2026-05-12 19:23:36+08'::timestamptz, updated_at = '2026-05-12 19:23:36+08'::timestamptz where id = '7324fc94-deac-5464-9782-25132a1b1822';
update vizserve_pms_task_comments set created_at = '2026-05-12 19:20:02+08'::timestamptz, updated_at = '2026-05-12 19:20:02+08'::timestamptz where id = 'cdf6ec49-24ff-56ae-a380-680d0586d68e';
update vizserve_pms_task_comments set created_at = '2026-06-10 21:40:38+08'::timestamptz, updated_at = '2026-06-10 21:40:38+08'::timestamptz where id = 'cb205cf5-db1b-551d-9db1-8e2d222efda2';
update vizserve_pms_task_comments set created_at = '2026-06-10 21:38:04+08'::timestamptz, updated_at = '2026-06-10 21:38:04+08'::timestamptz where id = '7a9d1f58-db18-53a0-989b-ac4075a42a44';
update vizserve_pms_task_comments set created_at = '2026-06-10 21:34:45+08'::timestamptz, updated_at = '2026-06-10 21:34:45+08'::timestamptz where id = '02f9650d-faff-556d-829b-449e9bb6543a';
update vizserve_pms_task_comments set created_at = '2026-06-10 21:32:15+08'::timestamptz, updated_at = '2026-06-10 21:32:15+08'::timestamptz where id = '50a7892e-d9a1-56d5-814b-c15952786287';
update vizserve_pms_task_comments set created_at = '2026-06-10 21:31:56+08'::timestamptz, updated_at = '2026-06-10 21:31:56+08'::timestamptz where id = 'db03788c-2686-56f5-9481-262c49f77afe';
update vizserve_pms_task_comments set created_at = '2026-06-10 21:29:58+08'::timestamptz, updated_at = '2026-06-10 21:29:58+08'::timestamptz where id = '8018d6f3-c439-500e-b596-c750bf74d4b5';
update vizserve_pms_task_comments set created_at = '2026-06-10 21:26:23+08'::timestamptz, updated_at = '2026-06-10 21:26:23+08'::timestamptz where id = '1cad027a-7dbc-5d81-aa65-ec651b38fb51';
update vizserve_pms_task_comments set created_at = '2026-06-10 21:22:21+08'::timestamptz, updated_at = '2026-06-10 21:22:21+08'::timestamptz where id = 'df5cd537-2c59-5f47-89e7-558b0d371947';
update vizserve_pms_task_comments set created_at = '2026-06-10 21:21:17+08'::timestamptz, updated_at = '2026-06-10 21:21:17+08'::timestamptz where id = 'd8f07bf6-3190-5a4f-8a6f-38a33fb3e922';
update vizserve_pms_task_comments set created_at = '2026-04-20 16:38:51+08'::timestamptz, updated_at = '2026-04-20 16:38:51+08'::timestamptz where id = '34b06bb1-0ec6-5534-8e0d-6844bb479120';
update vizserve_pms_task_comments set created_at = '2026-04-20 16:19:51+08'::timestamptz, updated_at = '2026-04-20 16:19:51+08'::timestamptz where id = '880b9885-fe82-59ff-b1e7-43ced32644e4';
update vizserve_pms_task_comments set created_at = '2026-01-13 17:30:08+08'::timestamptz, updated_at = '2026-01-13 17:30:08+08'::timestamptz where id = 'c8c3d7a9-5b9b-554e-a342-fcdd72f0dc92';
update vizserve_pms_task_comments set created_at = '2026-01-13 17:28:34+08'::timestamptz, updated_at = '2026-01-13 17:28:34+08'::timestamptz where id = '0d74e6d7-62e0-5067-b882-176641cdca57';
update vizserve_pms_task_comments set created_at = '2026-01-13 17:23:16+08'::timestamptz, updated_at = '2026-01-13 17:23:16+08'::timestamptz where id = '0b0703d2-1d06-557f-af6f-36277c251071';
update vizserve_pms_task_comments set created_at = '2026-01-13 17:18:17+08'::timestamptz, updated_at = '2026-01-13 17:18:17+08'::timestamptz where id = 'c60db113-4b52-53ed-8182-fb76957a901f';
update vizserve_pms_task_comments set created_at = '2026-01-13 17:15:37+08'::timestamptz, updated_at = '2026-01-13 17:15:37+08'::timestamptz where id = '3ece12f9-620f-541f-9d3d-816f79496078';
update vizserve_pms_task_comments set created_at = '2026-01-13 17:14:16+08'::timestamptz, updated_at = '2026-01-13 17:14:16+08'::timestamptz where id = 'df3b4f9f-1b90-541f-9d1d-f4e6001687f2';
update vizserve_pms_task_comments set created_at = '2026-01-13 17:12:40+08'::timestamptz, updated_at = '2026-01-13 17:12:40+08'::timestamptz where id = 'a432cac6-88ab-59d2-8356-359471637ae5';
update vizserve_pms_task_comments set created_at = '2026-01-13 17:09:59+08'::timestamptz, updated_at = '2026-01-13 17:09:59+08'::timestamptz where id = '54658d9a-3a8e-51cb-9694-f6a7796db3bd';
update vizserve_pms_task_comments set created_at = '2026-08-13 12:43:34+08'::timestamptz, updated_at = '2026-08-13 12:43:34+08'::timestamptz where id = '77c80118-121f-5b41-8ea0-7551170d9883';
update vizserve_pms_task_comments set created_at = '2026-08-13 12:40:08+08'::timestamptz, updated_at = '2026-08-13 12:40:08+08'::timestamptz where id = '4ae191de-b425-56ce-b9d3-85382e075b85';
update vizserve_pms_task_comments set created_at = '2026-08-13 12:38:13+08'::timestamptz, updated_at = '2026-08-13 12:38:13+08'::timestamptz where id = '3b7c9f34-721b-578c-a996-bf472ebd2563';
update vizserve_pms_task_comments set created_at = '2026-08-13 12:35:29+08'::timestamptz, updated_at = '2026-08-13 12:35:29+08'::timestamptz where id = '3d0b5089-76a5-58ce-9940-b3f2308937c3';
update vizserve_pms_task_comments set created_at = '2026-08-13 12:33:18+08'::timestamptz, updated_at = '2026-08-13 12:33:18+08'::timestamptz where id = 'ce036bc3-caba-5d1c-97f7-7a3486689f58';
update vizserve_pms_task_comments set created_at = '2026-08-13 12:32:35+08'::timestamptz, updated_at = '2026-08-13 12:32:35+08'::timestamptz where id = '95b6ef3c-425c-5104-a475-91495d3267bc';
update vizserve_pms_task_comments set created_at = '2026-07-10 19:29:21+08'::timestamptz, updated_at = '2026-07-10 19:29:21+08'::timestamptz where id = 'd2dc751c-dca0-566a-9935-186a563e59fb';
alter table vizserve_pms_task_comments enable trigger vizserve_pms_task_comments_updated_at;

commit;
